# Generated by Django 2.2.5 on 2019-09-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='comfavs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=50)),
                ('count', models.IntegerField(default=1)),
            ],
        ),
    ]
